import { NextRequest, NextResponse } from "next/server";
import type { JWTPayload } from "jose";

import { withAuth } from "@/lib/auth/with-auth";
import { getAgentRunById, getIssueById, getWorkspaceById, updateAgentRunBranch } from "@skynet/db";
import { getGitHubClient } from "@/lib/github/client";
import type { ApiErrorResponse } from "@skynet/sdk";

export const runtime = "nodejs";

export const POST = withAuth(
  async (
    _request: NextRequest,
    _user: JWTPayload,
    context: { params: Promise<Record<string, string>> },
  ): Promise<NextResponse> => {
    const params = await context.params;
    if (!params.id) {
      const body: ApiErrorResponse = {
        error: { code: "INVALID_REQUEST", message: "Agent run id is required" },
      };
      return NextResponse.json(body, { status: 400 });
    }

    try {
      const run = await getAgentRunById(params.id);
      if (!run) {
        const body: ApiErrorResponse = { error: { code: "NOT_FOUND", message: "Agent run not found" } };
        return NextResponse.json(body, { status: 404 });
      }

      if (run.status !== "completed") {
        const body: ApiErrorResponse = {
          error: { code: "INVALID_STATE", message: "Agent run must be completed before creating a PR" },
        };
        return NextResponse.json(body, { status: 409 });
      }

      if (run.prNumber) {
        return NextResponse.json({ prNumber: run.prNumber, alreadyExists: true });
      }

      if (!run.issueId) {
        const body: ApiErrorResponse = {
          error: { code: "INVALID_STATE", message: "Agent run has no associated issue" },
        };
        return NextResponse.json(body, { status: 400 });
      }

      // Resolve branch: prefer workspace branch, fall back to run.branch
      let branch = run.branch ?? null;
      if (!branch && run.workspaceId) {
        const workspace = await getWorkspaceById(run.workspaceId);
        branch = workspace?.branch ?? null;
      }

      if (!branch) {
        const body: ApiErrorResponse = {
          error: { code: "NO_BRANCH", message: "No branch found — make sure changes were committed and pushed" },
        };
        return NextResponse.json(body, { status: 400 });
      }

      const issueResult = await getIssueById(run.issueId);
      const issue = issueResult.issue;
      if (!issue) {
        const body: ApiErrorResponse = { error: { code: "NOT_FOUND", message: "Issue not found" } };
        return NextResponse.json(body, { status: 404 });
      }

      const github = getGitHubClient();
      const pr = await github.createPullRequest(issue.repoOwner, issue.repoName, {
        title: `fix: ${issue.title}`,
        body: [
          `Closes #${issue.number}`,
          "",
          "## Summary",
          issue.aiSummary ?? issue.body ?? "",
          "",
          `_Generated by Skynet agent run \`${run.id.slice(0, 8)}\`_`,
        ].join("\n"),
        head: branch,
        base: "main",
      });

      await updateAgentRunBranch(run.id, branch, pr.number);

      return NextResponse.json({ prNumber: pr.number, prUrl: pr.html_url });
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to create PR";
      const body: ApiErrorResponse = { error: { code: "PR_CREATE_ERROR", message } };
      return NextResponse.json(body, { status: 500 });
    }
  },
);
